language: python
python:
  - "2.7"
install:
    - sudo apt-get install swig
    - sudo pip install --upgrade pip
    - sudo apt-get install libusb-1.0-0-dev
    - pip install -r requirements.txt
script: python test/test_executor.py --github=t
branches:
  only:
    #- master
    - refactor