language: python
python:
  - "2.7"
before_install:
    - sudo apt-get install swig
    - sudo pip install --upgrade pip
    - pip install -r requirements.txt
script: python test/test_executor.py --github=t
branches:
  only:
    #- master
    - refactor
